version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
      # EC2 환경을 위한 추가 설정
      - SLACK_SOCKET_MODE_TIMEOUT=30
      - NOTION_API_TIMEOUT=15
    env_file:
      - .env
    volumes:
      - .:/app
    # EC2 환경 최적화를 위한 리소스 제한
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    # 헬스체크 추가
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:3000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 재시작 정책
    restart: unless-stopped
    
  # 스케줄러 서비스는 주석 처리 (현재 사용하지 않음)
  # scheduler:
  #   build: .
  #   command: python scheduler.py
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - web
  #   restart: unless-stopped

# 네트워크 설정 (EC2 환경 최적화)
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16